FROM openjdk:16-slim
MAINTAINER stupidzhang
ARG JAR_FILE=/target/*.jar
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
COPY ${JAR_FILE} /app.jar
EXPOSE 8180
HEALTHCHECK CMD curl -fs http://localhost:8180/health/check || exit 1
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar /app.jar"]
